export const roadmap = [
  {
    id: "arrays-hashing",
    title: "Arrays & Hashing",
    week: 1,
    days: "2 problems/day",
    tag: "Easiest start",
    tagColor: "#22c55e",
    watchFirst: "Arrays Introduction, 2D Arrays, ArrayList, HashMap & HashSet lectures",
    context: "Arrays & Hashing is where most easy problems live. Don't skip any — these show up in every company OA.",
    problems: [
      { id: "ah-1", name: "Contains Duplicate", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/contains-duplicate/" },
      { id: "ah-2", name: "Valid Anagram", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/valid-anagram/" },
      { id: "ah-3", name: "Two Sum", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/two-sum/" },
      { id: "ah-4", name: "Group Anagrams", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/group-anagrams/" },
      { id: "ah-5", name: "Top K Frequent Elements", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/top-k-frequent-elements/" },
      { id: "ah-6", name: "Product of Array Except Self", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/product-of-array-except-self/" },
      { id: "ah-7", name: "Encode & Decode Strings", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/encode-and-decode-strings/" },
      { id: "ah-8", name: "Longest Consecutive Sequence", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/longest-consecutive-sequence/" },
    ]
  },
  {
    id: "two-pointers",
    title: "Two Pointers",
    week: 2,
    days: "2 problems/day",
    tag: "Core pattern",
    tagColor: "#3b82f6",
    watchFirst: "Two Pointer technique video",
    context: "Two pointers is asked in almost every company. 3Sum and Trapping Rain Water are must-knows.",
    problems: [
      { id: "tp-1", name: "Valid Palindrome", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/valid-palindrome/" },
      { id: "tp-2", name: "Two Sum II", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/" },
      { id: "tp-3", name: "3Sum", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/3sum/" },
      { id: "tp-4", name: "Container With Most Water", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/container-with-most-water/" },
      { id: "tp-5", name: "Trapping Rain Water", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/trapping-rain-water/" },
    ]
  },
  {
    id: "sliding-window",
    title: "Sliding Window",
    week: 3,
    days: "2 problems/day",
    tag: "High frequency",
    tagColor: "#f59e0b",
    watchFirst: "Sliding Window video",
    context: "Min Window Substring is hard but asked by Razorpay, Flipkart, Amazon — don't skip it.",
    problems: [
      { id: "sw-1", name: "Best Time to Buy & Sell Stock", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
      { id: "sw-2", name: "Longest Substring Without Repeating Chars", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { id: "sw-3", name: "Longest Repeating Char Replacement", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/longest-repeating-character-replacement/" },
      { id: "sw-4", name: "Permutation in String", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/permutation-in-string/" },
      { id: "sw-5", name: "Minimum Window Substring", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/minimum-window-substring/" },
      { id: "sw-6", name: "Sliding Window Maximum", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/sliding-window-maximum/" },
    ]
  },
  {
    id: "stack-binary-search",
    title: "Stack & Binary Search",
    week: 4,
    days: "2 problems/day",
    tag: "Mid priority",
    tagColor: "#8b5cf6",
    watchFirst: "Stack introduction, Binary Search lecture",
    context: "Largest Rectangle in Histogram and Median of Two Sorted Arrays are hard but come up at Atlassian, Google.",
    problems: [
      { id: "sbs-1", name: "Valid Parentheses", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/valid-parentheses/" },
      { id: "sbs-2", name: "Min Stack", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/min-stack/" },
      { id: "sbs-3", name: "Reverse Polish Notation", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/evaluate-reverse-polish-notation/" },
      { id: "sbs-4", name: "Generate Parentheses", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/generate-parentheses/" },
      { id: "sbs-5", name: "Daily Temperatures", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/daily-temperatures/" },
      { id: "sbs-6", name: "Car Fleet", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/car-fleet/" },
      { id: "sbs-7", name: "Largest Rectangle in Histogram", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
      { id: "sbs-8", name: "Binary Search", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/binary-search/" },
      { id: "sbs-9", name: "Search 2D Matrix", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/search-a-2d-matrix/" },
      { id: "sbs-10", name: "Koko Eating Bananas", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/koko-eating-bananas/" },
      { id: "sbs-11", name: "Find Min in Rotated Sorted Array", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" },
      { id: "sbs-12", name: "Search in Rotated Sorted Array", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
      { id: "sbs-13", name: "Median of Two Sorted Arrays", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
    ]
  },
  {
    id: "linked-list",
    title: "Linked List",
    week: 5,
    days: "2 problems/day",
    tag: "Pointers practice",
    tagColor: "#ec4899",
    watchFirst: "Linked List intro, Doubly linked list, Fast & slow pointer",
    context: "LRU Cache = HashMap + Doubly Linked List combined — very common interview question.",
    problems: [
      { id: "ll-1", name: "Reverse Linked List", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/reverse-linked-list/" },
      { id: "ll-2", name: "Merge Two Sorted Lists", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/merge-two-sorted-lists/" },
      { id: "ll-3", name: "Reorder List", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/reorder-list/" },
      { id: "ll-4", name: "Remove Nth Node from End", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
      { id: "ll-5", name: "Copy List with Random Pointer", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
      { id: "ll-6", name: "Add Two Numbers", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/add-two-numbers/" },
      { id: "ll-7", name: "Find Duplicate Number", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/find-the-duplicate-number/" },
      { id: "ll-8", name: "LRU Cache", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/lru-cache/" },
      { id: "ll-9", name: "Merge K Sorted Lists", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/merge-k-sorted-lists/" },
      { id: "ll-10", name: "Reverse Nodes in K-Group", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/reverse-nodes-in-k-group/" },
      { id: "ll-11", name: "Linked List Cycle", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/linked-list-cycle/" },
    ]
  },
  {
    id: "trees",
    title: "Trees",
    week: 6,
    days: "2 problems/day",
    tag: "Most asked",
    tagColor: "#10b981",
    watchFirst: "Binary Tree intro, BST, Tree traversals, Level order traversal",
    context: "Trees are the #1 most asked topic in Indian product companies. Spend extra time here — it pays off most.",
    problems: [
      { id: "tr-1", name: "Invert Binary Tree", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/invert-binary-tree/" },
      { id: "tr-2", name: "Max Depth of Binary Tree", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
      { id: "tr-3", name: "Diameter of Binary Tree", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/diameter-of-binary-tree/" },
      { id: "tr-4", name: "Balanced Binary Tree", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/balanced-binary-tree/" },
      { id: "tr-5", name: "Same Tree", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/same-tree/" },
      { id: "tr-6", name: "Subtree of Another Tree", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/subtree-of-another-tree/" },
      { id: "tr-7", name: "LCA of BST", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
      { id: "tr-8", name: "Binary Tree Level Order Traversal", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
      { id: "tr-9", name: "Right Side View", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/binary-tree-right-side-view/" },
      { id: "tr-10", name: "Count Good Nodes", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/" },
      { id: "tr-11", name: "Validate BST", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/validate-binary-search-tree/" },
      { id: "tr-12", name: "Kth Smallest in BST", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
      { id: "tr-13", name: "Construct Tree from Preorder & Inorder", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
      { id: "tr-14", name: "Binary Tree Max Path Sum", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
      { id: "tr-15", name: "Serialize & Deserialize Binary Tree", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
    ]
  },
  {
    id: "heap-tries",
    title: "Heap & Tries",
    week: 7,
    days: "2 problems/day",
    tag: "Good differentiator",
    tagColor: "#f97316",
    watchFirst: "Priority Queue / Heap video, Trie lecture",
    context: "Design Twitter combines heap + hashtable — great project-level thinking question, often asked at startups.",
    problems: [
      { id: "ht-1", name: "Kth Largest Element in Array", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
      { id: "ht-2", name: "Last Stone Weight", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/last-stone-weight/" },
      { id: "ht-3", name: "K Closest Points to Origin", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/k-closest-points-to-origin/" },
      { id: "ht-4", name: "Task Scheduler", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/task-scheduler/" },
      { id: "ht-5", name: "Design Twitter", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/design-twitter/" },
      { id: "ht-6", name: "Find Median from Data Stream", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/find-median-from-data-stream/" },
      { id: "ht-7", name: "Implement Trie", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/implement-trie-prefix-tree/" },
      { id: "ht-8", name: "Design Add & Search Words", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/design-add-and-search-words-data-structure/" },
      { id: "ht-9", name: "Word Search II", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/word-search-ii/" },
    ]
  },
  {
    id: "graphs",
    title: "Graphs",
    week: 8,
    days: "2 problems/day",
    tag: "High value",
    tagColor: "#06b6d4",
    watchFirst: "Graph intro, BFS, DFS, Topological sort",
    context: "Number of Islands + Course Schedule are asked in literally every company. Must-solve.",
    problems: [
      { id: "gr-1", name: "Number of Islands", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/number-of-islands/" },
      { id: "gr-2", name: "Clone Graph", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/clone-graph/" },
      { id: "gr-3", name: "Max Area of Island", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/max-area-of-island/" },
      { id: "gr-4", name: "Pacific Atlantic Water Flow", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/pacific-atlantic-water-flow/" },
      { id: "gr-5", name: "Surrounded Regions", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/surrounded-regions/" },
      { id: "gr-6", name: "Rotting Oranges", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/rotting-oranges/" },
      { id: "gr-7", name: "Walls and Gates", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/walls-and-gates/" },
      { id: "gr-8", name: "Course Schedule", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/course-schedule/" },
      { id: "gr-9", name: "Course Schedule II", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/course-schedule-ii/" },
      { id: "gr-10", name: "Redundant Connection", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/redundant-connection/" },
      { id: "gr-11", name: "Number of Connected Components", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/" },
      { id: "gr-12", name: "Valid Tree", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/graph-valid-tree/" },
      { id: "gr-13", name: "Word Ladder", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/word-ladder/" },
    ]
  },
  {
    id: "dynamic-programming",
    title: "Dynamic Programming",
    week: 9,
    days: "2 problems/day",
    tag: "Hardest section",
    tagColor: "#ef4444",
    watchFirst: "DP intro, Memoization vs tabulation, 0/1 Knapsack",
    context: "Climbing Stairs through Coin Change are the 'easy DP' problems every company asks. Nail those first.",
    problems: [
      { id: "dp-1", name: "Climbing Stairs", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/climbing-stairs/" },
      { id: "dp-2", name: "Min Cost Climbing Stairs", difficulty: "Easy", leetcodeUrl: "https://leetcode.com/problems/min-cost-climbing-stairs/" },
      { id: "dp-3", name: "House Robber", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/house-robber/" },
      { id: "dp-4", name: "House Robber II", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/house-robber-ii/" },
      { id: "dp-5", name: "Longest Palindromic Substring", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { id: "dp-6", name: "Palindromic Substrings", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/palindromic-substrings/" },
      { id: "dp-7", name: "Decode Ways", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/decode-ways/" },
      { id: "dp-8", name: "Coin Change", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/coin-change/" },
      { id: "dp-9", name: "Maximum Product Subarray", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/maximum-product-subarray/" },
      { id: "dp-10", name: "Word Break", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/word-break/" },
      { id: "dp-11", name: "Longest Increasing Subsequence", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/longest-increasing-subsequence/" },
      { id: "dp-12", name: "Partition Equal Subset Sum", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/partition-equal-subset-sum/" },
      { id: "dp-13", name: "Unique Paths", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/unique-paths/" },
      { id: "dp-14", name: "Longest Common Subsequence", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/longest-common-subsequence/" },
      { id: "dp-15", name: "Edit Distance", difficulty: "Medium", leetcodeUrl: "https://leetcode.com/problems/edit-distance/" },
      { id: "dp-16", name: "Burst Balloons", difficulty: "Hard", leetcodeUrl: "https://leetcode.com/problems/burst-balloons/" },
    ]
  },
];

export const totalProblems = roadmap.reduce((acc, s) => acc + s.problems.length, 0);
